apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ty38
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ty38
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ty38
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ty38
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ty38
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/happy-path-sxuz-tenant/appstudio/dc-metro-map-ty38@sha256:91e51f84bc7ae8e5deace11ff9c1c058f0e7b9f2e0399ae7529c60e4ae4a8152
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
